title: Jekyll Test
email: blog@benjaminoakes.com
description: >
  Just testing out Jekyll.
baseurl: ""
url: ""
twitter_username: benjaminoakes
github_username:  benjaminoakes

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
