title: Benjamin Oakes
email: blog@benjaminoakes.com
description: >
  A programmer, sustainability enthusiast, and community builder in Iowa City.
baseurl: "https://benjaminoakes.github.io/ghpages-test/"
url: "https://benjaminoakes.github.io/ghpages-test/"
twitter_username: benjaminoakes
github_username:  benjaminoakes

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
