title: Benjamin Oakes
description: >
  A programmer, sustainability enthusiast, and community builder in Iowa City.
url: "https://benjaminoakes.github.io/"
twitter_username: benjaminoakes
github_username:  benjaminoakes
permalink: ':year/:month/:day/:title'

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
